In [31]:
#Que1.

import pandas as pd
course_name = ['Data Science', 'Machine Learning', 'Big Data', 'Data Engineer']
duration = [2,3,6,4]
df = pd.DataFrame(data = {'course_name' : course_name, 'duration' : duration})
df

        course_name  duration
0      Data Science         2
1  Machine Learning         3
2          Big Data         6
3     Data Engineer         4

In [32]:
df.loc[1]

course_name    Machine Learning
duration                      3
Name: 1, dtype: object

#Que2.

loc is a label-based indexing method that is used to access rows and columns by labels or boolean arrays. The syntax of the loc method is df.loc[row_labels, column_labels]. Here, row_labels and column_labels refer to the row and column labels, respectively. loc returns a DataFrame that matches the specified labels.

iloc on the other hand, is an integer-based indexing method that is used to access rows and columns by integer position. The syntax of the iloc method is df.iloc[row_positions, column_positions]. Here, row_positions and column_positions refer to the integer positions of the rows and columns, respectively. iloc returns a DataFrame that matches the specified integer positions.

In [33]:
#Que3.

reindex = [3,0,1,2]

new_df = df.reindex(reindex)
new_df

        course_name  duration
3     Data Engineer         4
0      Data Science         2
1  Machine Learning         3
2          Big Data         6

In [34]:
new_df.loc[2]

course_name    Big Data
duration              6
Name: 2, dtype: object

In [35]:
new_df.iloc[2]

course_name    Machine Learning
duration                      3
Name: 1, dtype: object

In [36]:
#Que4.
import numpy as np
columns = ['column_1', 'column_2', 'column_3', 'column_4', 'column_5', 'column_6']
indices = [1,2,3,4,5,6]
#Creating a dataframe:
df1 = pd.DataFrame(np.random.rand(6,6), columns = columns, index = indices)
df1

   column_1  column_2  column_3  column_4  column_5  column_6
1  0.969574  0.745133  0.044995  0.357344  0.718445  0.522603
2  0.327044  0.670316  0.270145  0.862883  0.200409  0.689738
3  0.591978  0.144366  0.763045  0.730784  0.479515  0.232710
4  0.332293  0.342548  0.642183  0.304477  0.485272  0.066556
5  0.525238  0.908101  0.732696  0.656078  0.986665  0.956791
6  0.714846  0.179808  0.660666  0.117352  0.943291  0.697396

In [37]:
means=[]

for each_col in list(df1.columns):
    means.append(df1[each_col].mean())

print(f"Mean of each column: {means}")
print(f"Standard Deviation of column_2: {df1['column_2'].std()}")

Mean of each column: [0.5768287908542628, 0.49837869367620374, 0.518954916454791, 0.5048198031796665, 0.635599534986088, 0.5276322450535518]
Standard Deviation of column_2: 0.319192128038402

In [38]:
df1['column_2'].loc[2]='new_val'

df1

   column_1  column_2  column_3  column_4  column_5  column_6
1  0.969574  0.745133  0.044995  0.357344  0.718445  0.522603
2  0.327044   new_val  0.270145  0.862883  0.200409  0.689738
3  0.591978  0.144366  0.763045  0.730784  0.479515  0.232710
4  0.332293  0.342548  0.642183  0.304477  0.485272  0.066556
5  0.525238  0.908101  0.732696  0.656078  0.986665  0.956791
6  0.714846  0.179808  0.660666  0.117352  0.943291  0.697396

In [ ]:
#Que9.

df= pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [40]:

filepath = input('Enter the filepath: ')
column = input('Enter the column name: ')
order = input('Enter category order: ')

df = pd.read_csv(filepath)

df[column].astype('category')

if order=='ascending':
    df=df.sort_values(by = column, ascending= True)
elif order=='descending':
    df=df.sort_values(by = column, ascending= False)

df

Enter the filepath: https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv
Enter the column name: Pclass
Enter category order: ascending

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
445,446,1,1,"Dodge, Master. Washington",male,4.0,0,2,33638,81.8583,A34,S
310,311,1,1,"Hays, Miss. Margaret Bechstein",female,24.0,0,0,11767,83.1583,C54,C
309,310,1,1,"Francatelli, Miss. Laura Mabel",female,30.0,0,0,PC 17485,56.9292,E36,C
307,308,1,1,"Penasco y Castellana, Mrs. Victor de Satode (M...",female,17.0,1,0,PC 17758,108.9000,C65,C
306,307,1,1,"Fleming, Miss. Margaret",female,NaN,0,0,17421,110.8833,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
379,380,0,3,"Gustafsson, Mr. Karl Gideon",male,19.0,0,0,347069,7.7750,NaN,S
381,382,1,3,"Nakid, Miss. Maria (""Mary"")",female,1.0,0,2,2653,15.7417,NaN,C
382,383,0,3,"Tikkanen, Mr. Juho",male,32.0,0,0,STON/O 2. 3101293,7.9250,NaN,S
371,372,0,3,"Wiklund, Mr. Jakob Alfred",male,18.0,1,0,3101267,6.4958,NaN,S
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [44]:
#Que10.
import pandas as pd
filepath = input('Enter filepath: ')

df = pd.read_csv(filepath)
df['Date'] = pd.to_datetime(df['Date'])
grouped = df.groupby(['Product', 'Date']).sum()
pivot = grouped.unstack(level=0)
pivot.plot(kind='bar', stacked=True)

#entered filepath: Product_sales.csv

Enter filepath:  Product_sales.csv

FileNotFoundError: [Errno 2] No such file or directory: ' Product_sales.csv'

In [45]:
#Que11.

filepath = input('Enter Filepath: ')

df = pd.read_csv(filepath)

mean = df['Test_Score'].mean()
median = df['Test_Score'].median()
mode = df['Test_Score'].mode()

print("+----------+----------+")
print("Statistic | Value")
print(f"Mean:    {mean}")
print(f"Median:    {median}")
print(f"Mode:    {mode}")
print("+----------+----------+")

#entered fiepath: students_data.csv

Enter Filepath:  students_data.csv

FileNotFoundError: [Errno 2] No such file or directory: ' students_data.csv'